import {
  AntDesign,
  Entypo,
  FontAwesome,
  FontAwesome5,
  FontAwesome6,
  Fontisto,
  Ionicons,
  MaterialCommunityIcons,
  MaterialIcons,
  Octicons,
} from '@expo/vector-icons';
import React from 'react';
import colors from '../assets/colors';
import sizes from '../constants/sizes';

const icons = {
  email: (size = sizes.icons.lg, color = colors.neutral[100]) => <Ionicons name="mail" size={size} color={color} />,
  gmail: (size = sizes.icons.lg, color = colors.neutral[100]) => <FontAwesome name="google" size={size} color={color} />,
  next: (size = sizes.icons.xl, color = colors.neutral[100]) => <AntDesign name="right" size={size} color={color} />,
  back: (size = sizes.icons.xl, color = colors.primary) => <AntDesign name="left" size={size} color={color} />,
  eye: (isSecuredText: boolean, size = sizes.icons.lg, color = colors.neutral[100]) => <Ionicons name={isSecuredText ? 'eye-off' : 'eye'} size={size} color={color} />,
  check: (size = sizes.icons.md, color = colors.neutral[100]) => <Entypo name="check" size={size} color={color} />,
  active: (size = sizes.icons.lg, color = colors.primary) => <Ionicons name="radio" size={size} color={color} />,
  filter: (size = sizes.icons.lg, color = colors.neutral[100]) => <Ionicons name="filter" size={size} color={color} />,
  search: (name: string, size = sizes.icons.lg, color = colors.black) => <Ionicons name={name} size={size} color={color} />,
  chat: (name: string, size = sizes.icons.lg, color = colors.black) => <Ionicons name={name} size={size} color={color} />,
  activity: (name: string, size = sizes.icons.lg, color = colors.black) => <MaterialIcons name={name} size={size} color={color} />,
  profile: (name: string, size = sizes.icons.lg, color = colors.black) => <Ionicons name={name} size={size} color={color} />,
  add: (name: string, size = sizes.icons.lg, color = colors.black) => <Ionicons name={name} size={size} color={color} />,
  star: (size = sizes.icons.md, color = colors.primary) => <Entypo name="star" size={size} color={color} />,
  pin: (size = sizes.icons.md, color = colors.primary) => <FontAwesome6 name="map-pin" size={size} color={color} />,
  date: (size = sizes.icons.md, color = colors.primary) => <Fontisto name="date" size={size} color={color} />,
  person: (size = sizes.icons.xxl, color = colors.neutral[100]) => <Octicons name="person" size={size} color={color} />,
  house: (size = sizes.icons.md, color = colors.primary) => <FontAwesome6 name="house" size={size} color={color} />,
  hand: (size = sizes.icons.md, color = colors.primary) => <Entypo name="hand" size={size} color={color} />,
  checked: (size = sizes.icons.md, color = colors.primary) => <FontAwesome5 name="check" size={size} color={color} />,
  close: (size = sizes.icons.xl, color = colors.neutral[400]) => <AntDesign name="close" size={size} color={color} />,
  close_modal: (size = sizes.icons.xxl, color = colors.neutral[400]) => <AntDesign name="close" size={size} color={color} />,
  marker: (size = sizes.icons.extra, color = colors.primary) => <MaterialCommunityIcons name="map-marker" size={size} color={color} />,
  edit: (size = sizes.icons.md, color = colors.primary) => <AntDesign name="edit" size={size} color={color} />,
  bookmark: (size = sizes.icons.lg, color = colors.neutral[500]) => <MaterialIcons name="bookmark-added" size={size} color={color} />,
  arrow_right: (size = sizes.icons.lg, color = colors.primary) => <MaterialCommunityIcons name="arrow-right-top-bold" size={size} color={color} />,
  logout: (size = sizes.icons.lg, color = colors.primary) => <MaterialIcons name="logout" size={size} color={color} />,
  delete: (size = sizes.icons.lg, color = colors.feedback.error) => <MaterialIcons name="delete-outline" size={size} color={color} />,
  meters: (size = sizes.icons.lg, color = colors.primary) => <Ionicons name="cube-outline" size={size} color={color} />,
  approximate: (size = sizes.icons.lg, color = colors.primary) => <MaterialCommunityIcons name="approximately-equal" size={size} color={color} />,
  dot: (size = sizes.icons.md, color = colors.primary) => <Entypo name="dot-single" size={size} color={color} />,
  photo: (size = sizes.icons.lg, color = colors.neutral[300]) => <FontAwesome name="photo" size={size} color={color} />,
  arrowRight: (size = sizes.icons.lg, color = colors.primary) => <MaterialCommunityIcons name="arrow-right" size={size} color={color} />,
  arrowLeft: (size = sizes.icons.lg, color = colors.primary) => <MaterialCommunityIcons name="arrow-left" size={size} color={color} />,
  hashtag: (size = sizes.icons.sm, color = colors.primary) => <Fontisto name="hashtag" size={size} color={color} />,
  quoteLeft: (size = sizes.icons.sm, color = colors.neutral[300]) => <FontAwesome5 name="quote-left" size={size} color={color} />,
  quoteRight: (size = sizes.icons.sm, color = colors.neutral[300]) => <FontAwesome5 name="quote-right" size={size} color={color} />,
  plus: (size = sizes.icons.lg, color = colors.neutral[400]) => <FontAwesome6 name="plus" size={size} color={color} />,
  minus: (size = sizes.icons.lg, color = colors.neutral[400]) => <FontAwesome6 name="minus" size={size} color={color} />,
  add_photo: (size = sizes.icons.xl, color = colors.primary) => <MaterialIcons name="add-to-photos" size={size} color={color} />,
  calendar: (size = sizes.icons.md, color = colors.primary) => <Entypo name="calendar" size={size} color={color} />,
  resend: (size = sizes.icons.xl, color = colors.neutral[100]) => <AntDesign name="sync" size={size} color={color} />,
  phone: (size = sizes.icons.xl, color = colors.neutral[100]) => <Ionicons name="call" size={size} color={color} />,
  needsEquipment: (size = sizes.icons.md, color = colors.primary) => <MaterialIcons name="cleaning-services" size={size} color={color} />,
};

export default icons;
